
export const AppScreen = {
  SPLASH: 'splash',
  LOGIN: 'login',
  HOME: 'home',
  SEARCH: 'search',
  HIRE_SEARCH: 'hire_search',
  DETAILS: 'details',
  TALENT_DETAILS: 'talent_details',
  FAVORITES: 'favorites',
  CHATS: 'chats',
  MENU: 'menu',
  PROFILE: 'profile',
  TRACKER: 'tracker',
  RECRUITER_DASHBOARD: 'recruiter_dashboard',
  POST_JOB: 'post_job',
  ADMIN_LOGIN: 'admin_login',
  ADMIN: 'admin',
  AI_COACH: 'ai_coach',
  COMPANY_PROFILE: 'company_profile',
  PACKAGE_SELECTION: 'package_selection',
  PAYMENT_METHOD: 'payment_method',
  RECRUITER_AUTH: 'recruiter_auth',
  PRIVACY_POLICY: 'privacy_policy',
  TERMS_CONDITIONS: 'terms_conditions',
  RETURN_POLICY: 'return_policy',
  REFUND_POLICY: 'refund_policy',
  ALL_CATEGORIES: 'all_categories',
  SERVICE_DETAILS: 'service_details',
  ROLE_SELECTION: 'role_selection'
};
